# Generated by Django 4.2.11 on 2024-06-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='korisnik',
            managers=[
            ],
        ),
    ]
