# Generated by Django 4.2.11 on 2024-06-10 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upis', '0004_remove_predmet_ects_bodovi_remove_predmet_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='nositelj',
            field=models.ForeignKey(limit_choices_to={'uloga__naziv': 'profesor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predmeti', to=settings.AUTH_USER_MODEL),
        ),
    ]
